### ISSUE TITLE
Does not work with remote projects

### ISSUE THREAD

**Issue by bichonnages** [wakatime/WakaTime.novaextension#1]
Hi!

Thanks for the great tool btw.
I am using the brand new Nova and I installed the Wakatime extensions.
From what I can see, it is not working with remote projects (on (s)FTP servers) :

`{"now": "2020/10/09 16:52:12 +0200", "version": "13.0.7", "plugin": "nova/1.2 nova-wakatime/1.0.3", "time": 1602255132.2309692, "caller": "wakatime/main.py", "lineno": 68, "is_write": true, "file": "/new/wp-content/themes/octave/single.php", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}`

Thanks for the help!

**Comment by bichonnages** [comment]
Hi! Any update on this issue? ☀️

**Comment by EllieLockhart** [comment]
Having this issue. I could try to debug/fix this myself, but I'd need confirmation it's an issue with the plugin and not something deeper. Like, I suspect VSCode (which I so want to stop using) avoids this by installing what amounts to code-server on the remote host, whereas as far as I can tell, Nova just makes an SSH connection and does everything else in the local OS X installation. If VSCode's way is the only solution, I worry this may not be solvable, at least for non-OS X remotes.

**Comment by EllieLockhart** [comment]
A thought: could the plugin be adjusted to make a local copy of the file or even a dummy file and send that file path to the plugin for heartbeats?

**Comment by alanhamlett** [comment]
@bichonnages I'll close this since we'll be implementing the solution from https://github.com/wakatime/WakaTime.novaextension/issues/2#issuecomment-732502571.
