### ISSUE TITLE
[Error] Cannot attach a stderr listener to a process that was not created using a pipe-based stderr

### ISSUE THREAD

**Issue by mikebronner** [wakatime/WakaTime.novaextension#10]
I saw the following error multiple times in the Extension Console after leaving Nova up overnight (my computer goes to sleep):
(Not sure if that has anything to do with it, just thought I'd mention it, in case.)

```
WakaTime[7:46:43.118000] Extension encountered an uncaught exception:
/Users/mike/Library/Application Support/Nova/Extensions/wakatime.timetracker/Scripts/main.js (Line 360, Column 0)
Error: Cannot attach a stderr listener to a process that was not created using a pipe-based stderr
    [native code]
    sendHeartbeat@file:///Users/mike/Library/Application%20Support/Nova/Extensions/wakatime.timetracker/Scripts/main.js:360:19
    onEvent@file:///Users/mike/Library/Application%20Support/Nova/Extensions/wakatime.timetracker/Scripts/main.js:320:18
```

The timestamps on the errors are from just a few minutes ago when I switched over to Nova for the first time this morning.

**Comment by alanhamlett** [comment]
Just released v2.0.3 to catch any errors when attaching stdout and stderr listeners. Hopefully that fixes it, but attaching the process exit listener might also fail. Let me know if it happens again and I'll re-open this issue!
