### ISSUE TITLE
Frequently crashes

### ISSUE THREAD

**Issue by EllieLockhart** [wakatime/WakaTime.novaextension#4]
During ordinary use (not related to the remote filesystem issue) Nova reports Wakatime has crashed and that either it, all extensions, or the editor must be reloading. This seems SOMEWHAT related to working with large files but I've had it happen elsewise. I don't have an exact time for the failure, but I'm *fairly* sure this is the debug message error.

`{"now": "2020/11/23 11:42:41 -0600", "version": "13.0.7", "plugin": "nova/3.1 nova-wakatime/1.0.3", "time": 1606153359.8669848, "caller": "wakatime/dependencies/__init__.py", "lineno": 145, "file": "/Users/ellie/Mount/jsonHarvesting/json-harvest-service-scripts/main.js", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.JavascriptParser"}`

I also wonder to what extent the debug mode itself is causing this.

Mostly it works, I just thought I'd bring this to folks' attention.

**Comment by alanhamlett** [comment]
That debug message is just a warning in `~/.wakatime.log`, probably unrelated. For a crash, there wouldn't be any logs in `~/.wakatime.log` but maybe in Nova's extension console? (`Extensions → Show Extension Console`)

**Comment by alanhamlett** [comment]
Closing because this looks like normal logging behavior.
